name:                salsa20
version:             0.1.0.0
github:              "oxarbitrage/hsalsa20"
license:             MIT
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oxarbitrage/hsalsa20#readme>

dependencies:
- base >= 4.7 && < 5
- split
- text
- keelung

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  
executables:
  salsa20-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa20
    - split
    - cryptohash-sha256
    - bytestring
    - nonce
    - base64-bytestring

tests:
  salsa20-fast-unit-tests:
    main:                Spec.hs
    source-dirs:         test/unit/fast
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa20
    - text
  salsa20-slow-unit-test:
    main:                Spec.hs
    source-dirs:         test/unit/slow
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa20
  salsa20-ecrypt256-tests:
    main:                Spec.hs
    source-dirs:         test/unit/ecrypt256
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa20
    - text
    - hex-text
    - bytestring
    - aeson
    - containers
  salsa20-ecrypt128-tests:
    main:                Spec.hs
    source-dirs:         test/unit/ecrypt128
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa20
    - text
    - hex-text
    - bytestring
    - aeson
    - containers
  salsa20-display-unit-tests:
    main:                Spec.hs
    source-dirs:         test/unit/display
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa20
    - HUnit
  salsa20-keelung-unit-tests:
    main:                Spec.hs
    source-dirs:         test/unit/keelung
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salsa20
    - HUnit
