name: Stack CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.2.8'
        enable-stack: true
        stack-version: 'latest'

    # install z3
    - name: Setup Z3
      id: z3
      uses: cda-tum/setup-z3@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install keelungc
      run: |
        git clone https://github.com/btq-ag/keelung-compiler
        cd keelung-compiler
        git fetch --all --tags
        git checkout tags/v0.19.1
        stack install

    - name: Move keelungc binary to /usr/local/bin/
      run: sudo mv $(stack path --local-bin)/keelungc /usr/local/bin/

    - uses: actions/cache@v1
      name: Cache .stack-work
      with:
        path: .stack-work
        key: stack-work

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: stack

    - name: Build
      run: stack build
    - name: Run fast tests
      run: stack test salsa20:test:salsa20-fast-unit-tests
    - name: Run ECRYPT 128 bits key size tests
      run: stack test salsa20:test:salsa20-ecrypt128-tests
    - name: Run ECRYPT 256 bits key size tests
      run: stack test salsa20:test:salsa20-ecrypt256-tests
    - name: Run display tests
      run: stack test salsa20:test:salsa20-display-unit-tests
    - name: Run keelung tests
      run: stack test salsa20:test:salsa20-keelung-unit-tests
